version: '3.0'

services:
  server:
    build: .
    ports:
      - "5000:5000"  
    command: npm run start

  webserver:
    image: nginx:alpine
    container_name: brok-webserver
    ports:
        - "80:80"
        - "443:443"

  db:
    image: postgres
    environment:
      - POSTGRES_USER=brok
      - POSTGRES_PASSWORD=brok
      - POSTGRES_DB=db_brok
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
