version: '3.0'

services:
  server:
    build: .
    ports:
      - "5000:5000"  
    volumes:
      - .:/usr/app
    command: npm run dev
    networks:
      - brok

  webserver:
    image: nginx:latest
    container_name: nginx
    ports:
        - "80:80"
        - "443:443"
    volumes:
      - ./nginx/node.conf:/etc/nginx/conf.d/node.template    
    command: 'bash -c "cat /etc/nginx/conf.d/node.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'
    working_dir: /usr/app
    networks:
      - brok

  db:
    image: postgres
    environment:
      - POSTGRES_USER=brok
      - POSTGRES_PASSWORD=brok
      - POSTGRES_DB=db_brok
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - brok

volumes:
  data:
networks:
    brok:
      
volumes:
  data:
      external: true
